name: Run Maven Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Load local Maven repository cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Vaadin Charts License
        run: echo "$VAADIN_LICENSE" > ~/.vaadin.charts.developer.license
        env:
          VAADIN_LICENSE: ${{ secrets.VAADIN_CHART_LICENSE_4 }} # Secrets are encrypted by default, when set as environment secrets


      - name: Run tests
        run: mvn clean verify
